### ISSUE TITLE
Source view strips out inline styling

### ISSUE THREAD

**Issue by chkelly** [volmer/bootsy#119]
If i use the source html view and add a `<p class=foo>this is a test</p>` it seems the class=foo bit is stripped out. Is there a way to prevent this from happening?

Also I noticed a previous issue (https://github.com/volmer/bootsy/issues/83) any plans to maybe switch to a better fork such as http://wysihtml.com/?

Otherwise the editor is great and one of the cleanest and best ones I have found.

**Comment by brettskiii** [comment]
+1 I'm getting the same thing here.. Is this expected behaviour?

**Comment by volmer** [comment]
Hey folks, sorry for the delay.

Yes, that's the expected behaviour as everything is parsed for security reasons. You must explicitly enable/disable elements, attributes and classes, otherwise they'll be stripped out. You can change `Bootsy.options.parserRules` in your app's js to achieve that. See https://github.com/volmer/bootsy/blob/master/app/assets/javascripts/bootsy/editor_options.js
