### ISSUE TITLE
Paste <script> tag into HTML mode

### ISSUE THREAD

**Issue by abelorian** [volmer/bootsy#132]
When a script tag is pasted in HTML mode, the line is deleted automatically.
¿How I can disable this feature?
I need to paste a Gist in a post .
Thanks.

**Comment by volmer** [comment]
That's the expected behaviour as everything is parsed for security reasons. You must explicitly enable/disable elements, attributes and classes, otherwise they'll be stripped out. You can change `Bootsy.options.parserRules` in your app's js to achieve that. See https://github.com/volmer/bootsy/blob/master/app/assets/javascripts/bootsy/editor_options.js

**Comment by abelorian** [comment]
Works fine! Thanks

**Comment by g00dL00Ks** [comment]
Quick question... sorry to ask something basic, but I've added the editor_option.js file above to my application.  How do I reference it when using my bootsy editor in a simple form?  I'm still getting the error where I can't paste in code into the HTML box.  thank you
