### ISSUE TITLE
Image upload is not displaying correctly

### ISSUE THREAD

**Issue by styrrcom** [volmer/bootsy#138]
Hi!
I'm using bootstrap app from [rails composer](https://github.com/RailsApps/rails-composer) with bootsy gem and bootsy image upload isn't displaying correctly.
Here is the screenshot of uploaded image.
![2015-05-24 15 04 48](https://cloud.githubusercontent.com/assets/8973543/7787773/6dede064-0226-11e5-911b-eb5dff420303.png)
Thumbnail is unclickable.

Code of the app [https://github.com/styrrcom/collaborative-blog](https://github.com/styrrcom/collaborative-blog)
Heroku demo [https://collaborative-blog.herokuapp.com/posts/new](https://collaborative-blog.herokuapp.com/posts/new)
Login: user@example.com pass: 12345678

**Comment by volmer** [comment]
Hi!

Do you have the same problem locally or it's just on Heroku? Where are you storing the uploaded files?

**Comment by styrrcom** [comment]
I have the same problem locally.
I think the problem is only in displaying images in uploader.

**Comment by volmer** [comment]
I see. If you give me the instructions on how to set up your app locally I can help you out.

**Comment by styrrcom** [comment]
Clone https://github.com/styrrcom/collaborative-blog  
Then in app folder run "bundle install", "rake db:create db:migrate db:seed".
After running "rails server" bootsy will be available at localhost:3000/posts/new
Login: user@example.com, pass: changeme

Thanks in advance!

**Comment by volmer** [comment]
Thanks for the information. I was able to find the problem. That's happening because you are overriding Bootstrap's `row` class here: https://github.com/styrrcom/collaborative-blog/blob/caa8f7bacc23389187b088dbb2618fb660ef524b/app/assets/stylesheets/posts.scss#L8-14

Bootsy relies on the grid system and classes provided by Bootstrap. I advise you to avoid changing those. You can always create and uses classes of your own.

**Comment by styrrcom** [comment]
Thanks a lot!
It's working!
