### ISSUE TITLE
Active Admin Support? 

### ISSUE THREAD

**Issue by atbyrd** [volmer/bootsy#143]
Is there any documentation related to how to use this with ActiveAdmin?

**Comment by volmer** [comment]
Hi!

I never tried ActiveAdmin, so there's no documentation about it at the moment.

**Comment by heliocola** [comment]
@volmer : ActiveAdmin uses formtastic instead of simple_form.
I tried bundling simple_form and bootsy together with ActiveAdmin but it doesn't work.

I am still trying to integrate it.

I suspect not, but have you tried integrating with formtastic before?
Have any idea or clue on how that can be done?
I can work on that code and send a PR. But at this point I am still in the hunt for a bootsy solution/integration with ActiveAdmin.

There is a wysiwyg editor for ActiveAdmin but is currently not being maintained and it doesn't work with the latest ActiveAdmin.

Thanks in advance.

**Comment by heliocola** [comment]
@atbyrd : what have you done? are you using any other gem or managed to integrate it inside ActiveAdmin?
I managed to create a custom (ActiveAdmin) member_action in my model, using a regular .html.erb file and integrated the bootsy.
I haven't finished, but that is an easy way I found to integrate rails way stuff into my ActiveAdmin projects.
@volmer : I can write off some documentation and create a sample ActiveAdmin app for reference.
I will keep you guys posted on my progress.

**Comment by volmer** [comment]
I never used ActiveAdmin so I can't help much, sorry. But if you ever figure out how to integrate Bootsy with it please share. It might help people on the same situation.

**Comment by heliocola** [comment]
@volmer : yesterday I finished the integration successfully!! Pretty much everything including the image gallery!
It works beautifully!!!
Thank you so much for this work.
I will sure share it!!! Should I create a page in the wiki? What you think is the best way?
I will also try a page on the ActiveAdmin website/wiki...
I pretty much work around a little bit of ActiveAdmin stuff to use exactly the code you have in your documentation (aka into a usual rails project).
To integrate it ActiveAdmin way you would have to support formtastic (as far as I could find out...)..

**Comment by volmer** [comment]
Cool! Glad to know you was able to integrate it. It would be great if you could add the instructions on the wiki.

**Comment by drc37** [comment]
@heliocola Are you still planning on putting together some documentation on how you did the integration with AA?

**Comment by heliocola** [comment]
@drc37 my apologies for the delay.
I've been postponing working on this for a while but I just took sometime to get something quickly.
Please check the wiki, let me know if you run into any issues.
