### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by henkholtrop** [volmer/bootsy#147]
Just a question. Why are you using the entire bootstrap collection? Why not just include the css needed to make it function. I'm not using you're gem now since it's giving me countless styling bugs.

**Comment by volmer** [comment]
I'm not sure if I got your question correctly, but Bootsy does not include Bootstrap. You have to add it yourself.

If you're asking about the requirement of the full library (css + js), that's because this gem is intended for Rails applications that are 100% on Bootstrap. Bootsy is not a standalone editor at the moment.
