### ISSUE TITLE
How to cusstomize icon ? 

### ISSUE THREAD

**Issue by max-si-m** [volmer/bootsy#158]
Hello, thanks for your gem. But I have some problem with it.
How I can change glyphicon icons to font awesome icons ?
I saw closed issues when you propose used glyphicon but in my project I use font awesome and glyphicon isn't needed.

**Comment by volmer** [comment]
Hi, thanks for using Bootsy!

You can do so on `master`, since I recently moved to [Bootstrap3-wysiwyg](https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg), which supports [Font-Awesome](https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg#font-awesome).

An approach would be to override Bootstrap3-wysiwyg's default options so you would have Font-Awesome enabled to all Bootsy areas:

```javascript
$(function(){
  $.fn.wysihtml5.defaultOptions.toolbar.fa = true;
});
```

**Comment by joaoribeirost** [comment]
Well, that line gives me an undefined error on .toolbar. Is there another i have it like this:
```
  $(document).on('ready page:load', function(){
    console.log($.fn.wysihtml5.defaultOptions.toolbar);
    $.fn.wysihtml5.defaultOptions.toolbar.fa = true;
  });
```
The console.log() prints undefined. 

Is there something i'm doing wrong, or was there a change?

**Comment by volmer** [comment]
@joaoribeirost Sorry, on the latest `2.2.1` the above snippet will no longer work since I rolled back Bootstrap3-wysihtml5 as it [is no longer maintained](https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg/pull/162). If you definitely need Font Awesome you can lock Bootsy `2.2.0` on your Gemfile.

**Comment by joaoribeirost** [comment]
Oh, okay then. Yeah, i need because i'm not installing all of bootstrap. Thanks! :)

**Comment by donkeydonkey** [comment]
Is there any way to customize the icons with your current version?

**Comment by volmer** [comment]
Unfortunately not at this point.

**Comment by donkeydonkey** [comment]
cool. i just did an @extend for each of the missing icons to extend the font awesome
