### ISSUE TITLE
InvalidAuthenticityToken when used in form

### ISSUE THREAD

**Issue by PavelJ** [volmer/bootsy#184]
Hi,
I just configured bootsy to be used in rails 4 application, but when I try to upload photo, I get the following error:
_Started POST "/bootsy/image_galleries/47/images" for ::1 at 2016-02-05 11:20:04 +0100_
_Processing by Bootsy::ImagesController#create as HTML_
_Parameters: {"image_gallery_id"=>"47"}_
_**Can't verify CSRF token authenticity**_
_Completed 422 Unprocessable Entity in 0ms (ActiveRecord: 0.0ms)_
FATAL -- : 
_**ActionController::InvalidAuthenticityToken** - ActionController::InvalidAuthenticityToken:_
_  actionpack (4.2.4) lib/action_controller/metal/request_forgery_protection.rb:181:in `handle_unverified_request'_

First thing I thought...ok, maybe bootsy cannot be inserted inside another form...but in your documentation you use it like "f.bootsy_area". I tried to remove token from the parent form etc. but I just can't get it to work. It almost looks, like the token is not send by bootsy or it's not permitted because of strong parameters. Could please point me in right direction? I guess this is not a bug, but just some misunderstanding on my side.

Thank you for your time and for this great editor.

**Comment by volmer** [comment]
Hi, can you share a sample application that reproduces the error?

**Comment by PavelJ** [comment]
I am trying to, but the most minimal project worked as expected, so I assume, it will be some configuration problem or some unexpected interaction between gems in my complex project. Now I am trying to slowly incorporate gems and configuration to my minimal project. I guess when I am able to reproduce it, I will know what caused it. I'll let you know.

**Comment by volmer** [comment]
It's really hard to figure out exactly if it's a bug or not without a sample application. Since you couldn't reproduce it on a minimal app I assume it's not a bug on Bootsy itself, so I'll close this issue.

For debug purposes you can disable the authenticity token check on your `ApplicationController` with an `only/except` or a `null_session`: http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection/ClassMethods.html

You can even change which controller Bootsy inherits from with this config:  https://github.com/volmer/bootsy/blob/master/lib/generators/bootsy/templates/bootsy.rb#L68

(instead of `ActionController::Base` you can point to your `ApplicationController` or even a separate one that skips the authenticity token verification completely).

**Comment by PavelJ** [comment]
Just for a future reference, problem was with order of javascript library includes. Bootsy has to be defined before jquery-filepload, with that setup, both works fine. Detail cam be found [here on stackoverflow](http://stackoverflow.com/questions/35309889/rails-form-doesnt-submit-any-data-during-ajax-call-file-upload-422-status)
