### ISSUE TITLE
Color doesn't change to black and image button can only hold a link

### ISSUE THREAD

**Issue by omarwaleed** [volmer/bootsy#194]
i have 2 problems.
first, whenever i change the color to anything but the default black and then choose black again the color in the text editor changes but the saved text doesn't. here's how it looks like
![untitled2](https://cloud.githubusercontent.com/assets/10861817/13884593/52cf8060-ed37-11e5-8ebd-3e3f16eae8f5.png)
![untitled](https://cloud.githubusercontent.com/assets/10861817/13884596/5329d696-ed37-11e5-8ad9-514e545756ae.png)
then i have another problem with the image upload showing the user only a text field for the user to enter a link and not an upload button

my bootsy initializer is as is i didnt change it

this is the first part of my application.css file
`/*
*= require_tree .
 *= require_self
 *= require foundation_and_overrides
 *= require bootsy
 */

 */
@import "bootstrap-sprockets";`

and my application.js
`
//= require jquery
//= require jquery_ujs

//= require bootstrap-sprockets
//= require bootsy
//= require foundation
//= require turbolinks
//= require_tree .
`

side question: there was an issue stating that users can't change the text alignment and there was some comments from one of the owners suggesting that it will soon be implemented. is it?
thanks

**Comment by volmer** [comment]
Hi there! Thanks for using Bootsy.

> first, whenever i change the color to anything but the default black and then choose black again the color in the text editor changes but the saved text doesn't.

I can confirm that's happening and it's a bug on Bootstrap-Wysihtml5, so the fix is out of the scope of this project. I'm planning on moving away from that lib as it is no longer maintained. In the mean time the best I can suggest is to disable `color`. I'll probably make that a default.

> then i have another problem with the image upload showing the user only a text field for the user to enter a link and not an upload button.

You need to rename your `application.css` to `application.scss` and use only `@import` statements to require your dependencies. When you do that, please make sure to import Bootsy *after* Bootstrap.

> there was an issue stating that users can't change the text alignment and there was some comments from one of the owners suggesting that it will soon be implemented. is it?

That's not on our roadmap for now.

**Comment by omarwaleed** [comment]
thank u for the quick reply. i followed your instructions regarding the image problem but it still persists
here's my new application.scss imports (file header)
`
@import "bootstrap-sprockets";
@import "bootstrap";
@import "bootsy";
@import "foundation_and_overrides";
`
i tried removing bootstrap but the bootsy area toolbar just turns into unstyled links.

**Comment by volmer** [comment]
What if you don't import `foundation_and_overrides`?

**Comment by omarwaleed** [comment]
unfortunately same problem happens

**Comment by volmer** [comment]
I will need a sample application that reproduces the error so I can investigate it. Can you provide one?

**Comment by omarwaleed** [comment]
i'll try creating one now and will post the link in the next comment

**Comment by omarwaleed** [comment]
i've created a repo to replicate the problem just go to root and u'll find it. thanks
https://github.com/omarwaleed/bootsy_test

**Comment by volmer** [comment]
Thanks for the sample app. 

The problem happens because you didn't quite follow the usage instructions present on the README:
https://github.com/volmer/bootsy#usage

Specifically, you need to include `Bootsy::Container` on your `Post` model. Also, you need to pass an instance of post to `form_for`.

As a sidenote, if you ever face exceptions related with Sprockets, add this line to your Gemfile and rum `bundle update`:
```ruby
gem 'sprockets-rails', '~> 2.3'
```

**Comment by omarwaleed** [comment]
thanks alot for the help it works :) that part about adding the new instance of post to the form_for instead of using :post made the uploader change but i was left with an error. updating the sprockets-rails made it fully functional and works perfectly. thanks a bunch
