### ISSUE TITLE
Image upload modal layout broken

### ISSUE THREAD

**Issue by Rynaro** [volmer/bootsy#201]
Hello everybody,

Actually I'm using bootsy in a helpdesk app, the installation and configuration of gem is so easy to do.
My bootsy editor loads smooth, and all text manipulation tools works fine, but the image upload modal show broken to me. See the screenshot below
![selection_026](https://cloud.githubusercontent.com/assets/5271543/14858145/4593752a-0c75-11e6-9734-05b962556320.png)

The others modals, works fine. Only the image upload modal shows broken.

The bootsy version that  app uses is 2.2.2 .

**Comment by Rynaro** [comment]
Oh, my bad.
This behaviour occurs only because my application doesn't have a English language as a option available. The only (and main) language available to use is Brazilian Portuguese. I create a "pt_BR" translation file, and the modal works fine.
I think, we don't have a way to avoid this problem? Ok, I found the problem, and make a solution. But, the gem needs a improvement to deal with these situations, right? 
:)

**Comment by volmer** [comment]
Hey! Thanks for bringing that up. The problem happens when missing translations are replaced with the default `span.missing_translation` tag that completely messes up with the modal markup.

I don't think this is supposed to be fixed on Bootsy, it's rather a behaviour that depends on how your Rails app is configured. I particularly recommend setting both `config.i18n.enforce_available_locales = true` and `config.action_view.raise_on_missing_translations = true` on your `config/application.rb`.
