### ISSUE TITLE
Uncaught TypeError: Cannot read property 'font_styles' of undefined

### ISSUE THREAD

**Issue by jdsampayo** [volmer/bootsy#24]
I'm getting this error with last version bootsy (1.2.0)

*Uncaught TypeError: Cannot read property 'font_styles' of undefined*

In the javascript file **bootstrap-wysihtml5.js?body=1:8**

var tpl = {
        "font-styles": function(locale, options) {

I have bootstrap 2.3.2

The textarea remains as a normal textarea, it got the classes of bootsy via the simple_form helper.

**Comment by driehuis** [comment]
I just ran into this as well, and it struck me as suboptimal, because it was not at all abvious what caused bootsy/wysihtml5 not to show up on the page at all.

I'd like to propose detecting the situation, logging it to the JavaScript console as "Bootsy wysihtml5 - No i18n for 'nl-NL' available, defaulting to 'en'" and living up to that promise.

I'm  not really a JS guru, but if I got it off the ground, would such a patch stand a chance of being accepted, to help the next one after me to run into this one?

**Comment by volmer** [comment]
@driehuis sure, please send me a pull request and I'll review it. That's weird though, Bootsy should always default to `en`.

**Comment by jdsampayo** [comment]
Can we simply add to the Documentation:

"If Bootsy finds the 'lang' attribute in the HTML tag, it will set his locale with that value automagically, be sure to add the respective locale files for Bootsy if you are using that attribute. If Bootsy doesn't find the locale files that is trying to set, it will silently fail to render. You can override this behavior with the option 'data-bootsy-locale' in each of your inputs."

Or something like that, sorry, I'm not native English speaker.

**Comment by volmer** [comment]
Actually Bootsy shouldn't fail to render. I'll reopen this and try to work on a fix.

**Comment by volmer** [comment]
It should be fixed now on `master`. I'll release a new version of the gem soon. Thanks, everyone!

**Comment by driehuis** [comment]
2.1.0 worked for me, straight out of the box. Thanks a bundle!
