### ISSUE TITLE
Bootsy editor does not display on mobile

### ISSUE THREAD

**Issue by thaddeusm** [volmer/bootsy#242]
I use the editor in three rails apps and the editor displays on desktop browsers but never on mobile.  Your own demo app has the same problem.

You closed my issue a few months ago even though this was not resolved.  Are you interested in fixing this issue?  If not, I need to find a new rich text editor.

**Comment by volmer** [comment]
If you check the activity in this repo you will realize that I am more than willing to help anyone facing trouble with the editor, as long as they are willing to collaborate with this project. 

I closed your issue because you didn't care to explain the details, explain the steps to reproduce, nor to narrow down the problem to a specific scenario. What else could I say to an issue that simply states that "it doesn't work on mobile" other than "yes it does"?

So the question here is: ***are you*** interested in getting help with your issue? If so then please start by providing a way to reproduce it, so I can check if there's in fact something wrong with Bootsy.

**Comment by thaddeusm** [comment]
Two months ago I included a screenshot of your own demo app displayed on Google Chrome on an Android phone.  No rich text editor appears.  It is the same on my iPad running Safari.
I cannot find any examples of the editor displaying on mobile devices.
So, when you ask me to give you a way to reproduce the error, I'm not sure what you mean.  Can you provide an example of it displaying on mobile?  By that, I don't mean resizing a desktop browser window.  If your own demo app has this problem, why do you need to worry about reproducing it?
 
 
  On Sun, Nov 6, 2016 at 7:10 AM, Volmer<notifications@github.com> wrote:   
If you check the activity in this repo you will realize that I am more than willing to help anyone facing trouble with the editor, as long as they are willing to collaborate with this project. 

I closed your issue because you didn't care to explain the details, explain the steps to reproduce, nor to narrow down the problem to a specific scenario. What else could I say to an issue that simply states that "it doesn't work on mobile" other than "yes it does"?

So the question here is: are you interested in getting help with your issue? If so then please start by providing a way to reproduce it, so I can check if there's in fact something wrong with Bootsy.

**Comment by thaddeusm** [comment]
Here is another mobile screenshot (Android) of the Bootsy-Demo app where the editor does not display:

![screenshot_20161106-074041](https://cloud.githubusercontent.com/assets/16508259/20035615/bdef98b6-a3f4-11e6-9994-7ee8c8f3c70a.png)

**Comment by volmer** [comment]
I was able to reproduce it on Android. But the problem also happens in [Bootstrap-WYSIHTML5](https://github.com/jhollingworth/bootstrap-wysihtml5), which is the underlying lib used by Bootsy to create the editor. Unfortunately there's nothing I can do in Bootsy's side. 

I have plans to replace Bootstrap-WYSIHTML5, but there's no timeline on that yet.
