### ISSUE TITLE
Validation failed boosty

### ISSUE THREAD

**Issue by fathiabdulrahim** [volmer/bootsy#243]
fix by changing Rails.application.config.active_record.belongs_to_required_by_default = false in initiliazers/new_framework_defaults.rb

**Comment by volmer** [comment]
No, that setting is not required to run Bootsy.

**Comment by fathiabdulrahim** [comment]
the problem arise when im using rails 5

**Comment by volmer** [comment]
The demo app uses Rails 5 and it is working fine, it seems: https://github.com/volmer/bootsy-demo

**Comment by fathiabdulrahim** [comment]
http://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html

**Comment by dnswus** [comment]
I got this issue as well and @fathiabdulrahim's solution works for me. @volmer, https://github.com/volmer/bootsy-demo is fine because it does not have `initiliazers/new_framework_defaults.rb`. All new Rails 5 app will have this file by default. Another way to solve this is to add `optional: true` to `belongs_to :bootsy_resource`. I have created a pull request (https://github.com/volmer/bootsy/pull/244) to solve this problem.
