### ISSUE TITLE
Update to fork as wysihtml5 isn't maintained any more

### ISSUE THREAD

**Issue by adeelejaz** [volmer/bootsy#260]
I found an annoying bug and debugging it took me wysihtml5. It seems the project is no longer maintained (last release in 2012) and as per the readme, it suggests to use the fork: https://github.com/Voog/wysihtml

The bug was if you press enter multiple times to add spacing, the cursor stays in top line even though the new lines are being added. This can lead to user believing newlines are not being added. I was able to reproduce this issue on the demo website of wysihtml5 but the fork Voog/wysihtml works as expected.

**Comment by volmer** [comment]
Yes, that's one of many bugs Wysihtml5 has. I can't simply move to the fork you mentioned because Bootsy actually uses [bootstrap-wysithtml5](https://github.com/jhollingworth/bootstrap-wysihtml5), which relies on the original, discontinued Wysihtml5 (Bootsttrap-wysithml5 itself was discontinued). At this point there isn't much I can do myself but I am open to anyone who wishes to work on moving Bootsy to a different JS library.
