### ISSUE TITLE
Deprecation: Selection API: addRange() ignores additional Ranges

### ISSUE THREAD

**Issue by 6temes** [volmer/bootsy#270]
I just opened this Issue in the `bootstrap-wysihtml5` repository because it seems that some parts of the code are being deprecated by modern browsers.

https://github.com/jhollingworth/bootstrap-wysihtml5/issues/386

The problem is that the JavaScript library seems abandoned, so I don't think that this will be fixed anytime soon. So, in my opinion, there are 3 posibilities:

- Fork `bootstrap-wysihtml5` and fix the errors (or find a good fork that is maintained)
- Replace the JS library and use some other that is being maintained such as `Trumbowyg`, ~~Redactor~~ (paid), `Ckeditor`, ~~Froala~~ (paid), `TinyMCE`, etc...
- Abandon this gem and recommend any other rails gem that uses a more modern JS library. It would be a pity to loose it though because this gem has a good integration with Carrierwave and Simpleform.

**Comment by volmer** [comment]
> Fork bootstrap-wysihtml5 and fix the errors (or find a good fork that is maintained)

Believe me, I tried multiple forks since the original Bootstrap-WYSIHTML5 was abandoned. The few reliable ones ended up unmaintained as well, a lot of frustration.

> Replace the JS library and use some other that is being maintained such as Trumbowyg, Redactor (paid), Ckeditor, Froala (paid), TinyMCE, etc...

I haven't found any similar library... More specifically, anything with the quality and simplicity that makes sense for this project. Besides, this would mean a complete rewrite of the gem, which I cannot afford currently.

> Abandon this gem and recommend any other rails gem that uses a more modern JS library. It would be a pity to loose it though because this gem has a good integration with Carrierwave and Simpleform.

I'm going with this option, unfortunately. I won't endorse any alternatives, though. Everyone is welcome to fork this repo and adapt things out, or to try other gems and plugins.
