### ISSUE TITLE
Upload images through editor using Reform form

### ISSUE THREAD

**Issue by aldefouw** [volmer/bootsy#273]
Hi!

First of all - this is a wonderful gem.  Thanks so much for creating it.

The problem I am having is that I cannot allow image uploads if I am using the Reform gem for my validation rather than using a straight model.

This is because I am submitting things like this:

`<%= simple_form_for @post_form, url: path do |f| %>
      <%= f.input :body, label: "Body Text", :as => :bootsy %>
      <%= f.button :submit, class: "btn btn-success" %>
<% end %>`

@post_form is a Reform object rather than a strict model, thus it is not receiving the Bootsy::Container include.

If I submitting using @post, which is the actual model, the image uploader works.

So I guess I'm wondering if what I am trying to do is even possible?  

I know that you need this within the model:
`include Bootsy::Container`

Is there some way I can include that code outside of a model?

**Comment by volmer** [comment]
Hey

You can only include `Bootsy::Container` in Active Record classes. A container is an active record that will own the images uploaded in a form. That's why the upload feature is disabled if you don't provide a proper container object. If your form object isn't a container then you can specify a container yourself:

```ruby
f.input :body, as: :bootsy, container: @an_actual_active_record_post_object
```

**Comment by aldefouw** [comment]
Wonderful.

That should do exactly what I need it to.  I really appreciate your prompt response!
